### ISSUE TITLE
jcenter shutdown

### ISSUE THREAD

**Issue by linsui** [izivkov/RemoteVideoCam#28]
https://jfrog.com/blog/jcenter-sunset/

**Comment by izivkov** [comment]
I create a brancg WebRTC to handle this issie. Since org.webrtc:google-webrtc:1.0.32006 is only available from jCentral, the options are to replace this library with something like "org.jitsi:webrtc:124.0.0", or include a jar of "google-webrtc" in the project. Using "org.jitsi:webrtc" caused some problem of unresoved functions, so I think I will build the jar next.

**Comment by licaon-kter** [comment]
> Using org.jitsi:webrtc caused some problems with unresolved functions, 

why?

> include a JAR of google-webrtc in the project

please don't include binaries

try to use webrtc from Maven, eg. https://central.sonatype.com/artifact/im.conversations.webrtc/webrtc-android/versions

**Comment by izivkov** [comment]
@licaon-kter @toliuweijing 

Thanks for the suggestion. 
```
// implementation 'org.webrtc:google-webrtc:1.0.32006'
implementation "im.conversations.webrtc:webrtc-android:119.0.1"
```
This builds the project, but I get an error at runtime:

```
java.lang.UnsatisfiedLinkError: No implementation found for long org.webrtc.SoftwareVideoEncoderFactory.nativeCreateFactory() (tried Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory and Java_org_webrtc_SoftwareVideoEncoderFactory_nativeCreateFactory__)
                                                                                                    	at org.webrtc.SoftwareVideoEncoderFactory.nativeCreateFactory(Native Method)
                                                                                                    	at org.webrtc.SoftwareVideoEncoderFactory.<init>(SoftwareVideoEncoderFactory.java:23)
                                                                                                    	at org.webrtc.DefaultVideoEncoderFactory.<init>(DefaultVideoEncoderFactory.java:20)
                                                                                                    	at org.avmedia.remotevideocam.display.customcomponents.VideoViewWebRTC.initializePeerConnectionFactory(VideoViewWebRTC.kt:150)
```
How can Iclude these native libraries? Thanks for your help.

**Comment by licaon-kter** [comment]
Unfortunately I can't help with the rest of the implementation.

Note that your old webrtc was from Aug 2020 and full of vulnerabilities, that aside, newer versions changed some stuff indeed. Hope you find a way to use it for this app.

**Comment by izivkov** [comment]
@licaon-kter 

Are you OK if we use this library: 

```org.webrtc:google-webrtc:1.0.30039```

from here:
```
maven {
            url 'https://raw.githubusercontent.com/alexgreench/google-webrtc/master'
        }
```

Maybe replace it in the future.

**Comment by licaon-kter** [comment]
No, not really, the list of accepted repos is here (jcenter will be removed soon): https://gitlab.com/fdroid/fdroidserver/-/blob/8cf4503a00f6e0ccb93f5a9089cf660f20b0045b/fdroidserver/scanner.py#L456-L475

also, using a 4 years old webrtc will get you a Knownvuln flag :( , ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11496

**Comment by toliuweijing** [comment]
Reording can fix the UnsatisfiedLinkError exception, because `PeerConnectionFactory.initialize` loads the native library into memory.
<img width="570" alt="image" src="https://github.com/user-attachments/assets/b7e4a238-a776-4fac-be7f-2330e92d8383">

<img width="829" alt="image" src="https://github.com/user-attachments/assets/319b0daa-e7d1-43fd-8669-0dd2b95c6906">

However, [the PR](https://github.com/toliuweijing/RemoteVideoCam/pull/18/files?diff=unified&w=0) still doesn't work due to native crash. Need to investigate more. cc @izivkov if you have more insight.

**Comment by izivkov** [comment]
@toliuweijing 
Yes, I got that far in branch WebRTC. 

I'm working if the OpenCV has something to do with requiring hardware support.

**Comment by toliuweijing** [comment]
> @toliuweijing 
> Yes, I got that far in branch WebRTC. 
> 
> I'm wondering if the OpenCV has something to do with requiring hardware support.

I don't think so. I didn't use any fancy CV stuff but of course you can verify by reverting the commit.

**Comment by izivkov** [comment]
@toliuweijing 

Any luck with the WebRTC library replacement?

**Comment by toliuweijing** [comment]
@izivkov appologize for late reply. I didn't have enough time to investigate this. My plan is to debug it by building a sample webRTC app using the new dependency "im.conversations.webrtc:webrtc-android:119.0.1". 

Will see if I get some time late this month or next month.

**Comment by izivkov** [comment]
No worries, thanks for the update!
